Repository agonyforge/arbitrader, pull requests merged in 2020-10, with the labels that each got.

#230 catch up on Spring and XChange versions
  build.gradle
Labels: dependencies

#229 Fix NPE on XData (v5.0.2) for Gemini Streaming Exchange when args is empy
  build.gradle
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
  src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
Labels: bug

#235 Log each arbitrage to a csv file
  build.gradle
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/model/ArbitrageLog.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: enhancement

#240 Add banner.txt with ASCII art saying "Arbitrader"
  src/main/resources/application.yaml
  src/main/resources/banner.txt
Labels: enhancement

#236 Send trade notifications asynchronously via email (issue #144)
  application.example.yaml
  build.gradle
  src/main/java/com/r307/arbitrader/Arbitrader.java
  src/main/java/com/r307/arbitrader/config/MailConfiguration.java
  src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
  src/main/java/com/r307/arbitrader/service/NotificationService.java
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: enhancement

#238 Switch to Amazon Corretto JDK 8 base images
  src/main/docker/codebuild/Dockerfile
  src/main/docker/local/Dockerfile
  src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
Labels: tech debt, testing

#242 Extracted some methods out of TradingService#tick and simplified a bit the flow
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: tech debt, testing

#246 fix entry volume computation
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug

#248 GitHub packages
  buildspec.yml
  src/main/docker/codebuild/Dockerfile
  src/main/docker/local/Dockerfile
Labels: enhancement

#249 push a latest tag to GHCR on PR merges
  buildspec.yml
Labels: tech debt

#250 GitHub packages
  buildspec.yml
Labels: tech debt
