Repository agonyforge/arbitrader, pull requests merged in 2020-12, with the labels that each got.

#289 Fix logger name for TradingService
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug

#286 Send logs to Discord (issue #247)
  application.example.yaml
  build.gradle
  src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
  src/main/java/com/r307/arbitrader/logging/DiscordAppender.java
  src/main/resources/discord-appender.xml
  src/main/resources/logback-spring.xml
Labels: enhancement, testing

#291 On/off toggle for each configured exchange
  application.example.yaml
  src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
Labels: enhancement

#293 Force a trade to open
  src/main/java/com/r307/arbitrader/service/ConditionService.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
Labels: enhancement

#287 Prevent the bot to enter an unknown state when receiving a 5XX response for a getOpenOrders request
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug

#295 Fee computation
  src/main/java/com/r307/arbitrader/Utils.java
  src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
  src/main/java/com/r307/arbitrader/config/ExecutorConfig.java
  src/main/java/com/r307/arbitrader/config/FeeComputation.java
  src/main/java/com/r307/arbitrader/config/JsonConfiguration.java
  src/main/java/com/r307/arbitrader/config/MailConfiguration.java
  src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
  src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
  src/main/java/com/r307/arbitrader/exception/OrderNotFoundException.java
  src/main/java/com/r307/arbitrader/logging/DiscordAppender.java
  src/main/java/com/r307/arbitrader/logging/SlackAppender.java
  src/main/java/com/r307/arbitrader/logging/SpringContextSingleton.java
  src/main/java/com/r307/arbitrader/service/ConditionService.java
  src/main/java/com/r307/arbitrader/service/ErrorCollectorService.java
  src/main/java/com/r307/arbitrader/service/ExchangeFeeCache.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/NotificationService.java
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
  src/main/java/com/r307/arbitrader/service/SpreadService.java
  src/main/java/com/r307/arbitrader/service/TickerService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventListener.java
  src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventPublisher.java
  src/main/java/com/r307/arbitrader/service/model/ActivePosition.java
  src/main/java/com/r307/arbitrader/service/model/Spread.java
  src/main/java/com/r307/arbitrader/service/model/TickerEvent.java
  src/main/java/com/r307/arbitrader/service/model/TradeCombination.java
  src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/TickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/TickerStrategyProvider.java
  src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
Labels: bug, enhancement

#296 resolve dependency PRs
  build.gradle
Labels: dependencies

#297 clean up unwanted artifacts after test class runs
  src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
Labels: bug

#298 add dependency for Binance
  build.gradle
Labels: dependencies, enhancement

#300 Feature/paper trading
  application.example.yaml
  src/main/java/com/r307/arbitrader/config/PaperConfiguration.java
  src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/paper/PaperAccountService.java
  src/main/java/com/r307/arbitrader/service/paper/PaperExchange.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
Labels: enhancement

#302 get currency scale from exchange metadata
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: enhancement
