Repository agonyforge/arbitrader, pull requests merged in 2020-11, with the labels that each got.

#253 Reactive way to calculate trades for tickers received via websockets
  build.gradle
  src/main/java/com/r307/arbitrader/Utils.java
  src/main/java/com/r307/arbitrader/config/AppConfig.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/SpreadService.java
  src/main/java/com/r307/arbitrader/service/TickerService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventListener.java
  src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventPublisher.java
  src/main/java/com/r307/arbitrader/service/model/TickerEvent.java
  src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/TickerStrategyProvider.java
  src/test/java/com/r307/arbitrader/ExchangeBuilder.java
  src/test/java/com/r307/arbitrader/service/ExchangeServiceTest.java
  src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
  src/test/java/com/r307/arbitrader/service/TickerServiceTest.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
  src/test/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategyTest.java
  src/test/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategyTest.java
  src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
Labels: enhancement

#265 Uncomment trading logic that was merged by mistake
  buildspec.yml
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug

#277 Fix subscribeAll throw NPE
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
Labels: bug

#280 correctly setup trade combinations
  src/main/java/com/r307/arbitrader/service/TickerService.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
Labels: bug

#281 some general cleanup
  src/main/java/com/r307/arbitrader/Utils.java
  src/main/java/com/r307/arbitrader/service/ConditionService.java
  src/main/java/com/r307/arbitrader/service/ErrorCollectorService.java
  src/main/java/com/r307/arbitrader/service/ExchangeFeeCache.java
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
  src/main/java/com/r307/arbitrader/service/TickerService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/model/ArbitrageLog.java
  src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
Labels: tech debt

#282 pass custom arguments to `getTicker()`
  src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
Labels: enhancement

#283 unify active position
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug, testing

#284 some updates to the example configuration
  application.example.yaml
Labels: tech debt
