Repository agonyforge/arbitrader, pull requests merged in 2021-02, with the labels that each got.

#332 Migrate to agonyforge organization
  README.md
  application.example.yaml
  build.gradle
  buildspec.yml
  docker-compose.yaml
  src/main/docker/codebuild/Dockerfile
  src/main/docker/local/Dockerfile
  src/main/java/com/r307/arbitrader/Utils.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
Labels: breaking, tech debt

#337 push docker images to new agonyforge organization
  buildspec.yml
Labels: tech debt

#333 Added paper trading functionality for streaming exchanges
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/paper/PaperStreamExchange.java
Labels: enhancement

#338 Enhance paper AccountInfo with balance info + paper trading FeeComputation.CLIENT
  application.example.yaml
  src/main/java/com/r307/arbitrader/config/PaperConfiguration.java
  src/main/java/com/r307/arbitrader/service/paper/PaperAccountService.java
  src/main/java/com/r307/arbitrader/service/paper/PaperExchange.java
  src/main/java/com/r307/arbitrader/service/paper/PaperStreamExchange.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
  src/test/java/com/r307/arbitrader/service/paper/PaperTradeServiceTest.java
Labels: enhancement

#341 Telegram support
  application.example.yaml
  src/main/java/com/r307/arbitrader/config/MailConfiguration.java
  src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
  src/main/java/com/r307/arbitrader/logging/DiscordAppender.java
  src/main/java/com/r307/arbitrader/service/NotificationService.java
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/telegram/TelegramClient.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: enhancement
