Repository agonyforge/arbitrader, pull requests merged in 2021-03, with the labels that each got.

#353 Remove duplicated '-' on the groupId when sending a message via Telegram
  src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
Labels: bug

#355 add emojis to record breaker log messages
  src/main/java/com/r307/arbitrader/service/SpreadService.java
Labels: enhancement

#360 fix stream binance bug due to homeCurrencies
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
Labels: blocked, bug

#326 Change the volume calculation so the trade stays market neutral
  src/main/java/com/r307/arbitrader/DecimalConstants.java
  src/main/java/com/r307/arbitrader/config/MailConfiguration.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/NotificationService.java
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/model/EntryTradeVolume.java
  src/main/java/com/r307/arbitrader/service/model/ExitTradeVolume.java
  src/main/java/com/r307/arbitrader/service/model/TradeVolume.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
  src/test/java/com/r307/arbitrader/service/model/TradeVolumeTest.java
Labels: enhancement, testing

#363 Fixed record breaker logic and added tests
  src/main/java/com/r307/arbitrader/service/SpreadService.java
  src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
Labels: bug

#365 On TradingService#getVolumeForOrder null check volume and use currency.base scale instead of USD scale
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: bug

#366 remove assumptions about home currency and currency scales
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: tech debt

#367 Prevent the bot from starting up if the account wallet is not empty for any coin in the trading pair list
  src/main/java/com/r307/arbitrader/Utils.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: enhancement
