Repository agonyforge/arbitrader, pull requests merged in 2021-05, with the labels that each got.

#391 Use the CurrencyPairMetaData to find the price scale
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/test/java/com/r307/arbitrader/ExchangeBuilder.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: bug

#405 Prevent the bot from starting if an exchange account balance is lower than the defined fixed exposure
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
Labels: enhancement

#404 combined update to XChange 5.0.8
  build.gradle
Labels: dependencies, testing

#362 Bugfix: Send the whole message text when exiting a position due to timeout or forced exit command
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
Labels: bug

#408 Only fetch open orders for the exchange that actually has an open order
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: enhancement

#412 add order timers
  src/main/java/com/agonyforge/arbitrader/service/TradingService.java
Labels: enhancement
