Repository agonyforge/arbitrader, pull requests merged in 2021-04, with the labels that each got.

#374 configurable minimum balances
  application.example.yaml
  src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
Labels: bug, enhancement

#354 consolidate XChange version bumps into one PR
  build.gradle
Labels: dependencies

#370 Effective spreads
  application.example.yaml
  build.gradle
  src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
  src/main/java/com/r307/arbitrader/service/SpreadService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
Labels: breaking, enhancement, testing

#351 Bootstrap margin fee exchange configuration
  application.example.yaml
  build.gradle
  src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
  src/main/java/com/r307/arbitrader/exception/MarginNotSupportedException.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/SpreadService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/cache/ExchangeFeeCache.java
  src/main/java/com/r307/arbitrader/service/model/EntryTradeVolume.java
  src/main/java/com/r307/arbitrader/service/model/ExchangeFee.java
  src/main/java/com/r307/arbitrader/service/model/ExitTradeVolume.java
  src/main/java/com/r307/arbitrader/service/model/TradeVolume.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
  src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
  src/test/java/com/r307/arbitrader/service/cache/ExchangeFeeCacheTest.java
  src/test/java/com/r307/arbitrader/service/model/TradeVolumeTest.java
  src/test/java/com/r307/arbitrader/service/paper/PaperTradeServiceTest.java
Labels: breaking, enhancement, testing

#385 combined version bump to XChange 5.0.7
  build.gradle
Labels: dependencies
