Repository agonyforge/arbitrader, pull requests merged in 2021-01, with the labels that each got.

#303 misc changes
  .gitignore
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: tech debt

#304 refactor of ticker logic
  build.gradle
  src/main/java/com/r307/arbitrader/config/ExecutorConfig.java
  src/main/java/com/r307/arbitrader/service/TickerService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventListener.java
  src/main/java/com/r307/arbitrader/service/event/TickerEventListener.java
  src/main/java/com/r307/arbitrader/service/event/TickerEventPublisher.java
  src/main/java/com/r307/arbitrader/service/model/Spread.java
  src/main/java/com/r307/arbitrader/service/model/TickerEvent.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
  src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/TickerStrategy.java
  src/main/java/com/r307/arbitrader/service/ticker/TickerStrategyProvider.java
  src/test/java/com/r307/arbitrader/service/TickerServiceTest.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
  src/test/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategyTest.java
  src/test/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategyTest.java
  src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
Labels: tech debt

#305 Simplify and stabilize trade evaluation
  src/main/java/com/r307/arbitrader/exception/OrderNotFoundException.java
  src/main/java/com/r307/arbitrader/service/ConditionService.java
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
  src/main/java/com/r307/arbitrader/service/TickerService.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
  src/main/java/com/r307/arbitrader/service/cache/ExchangeBalanceCache.java
  src/main/java/com/r307/arbitrader/service/cache/ExchangeFeeCache.java
  src/main/java/com/r307/arbitrader/service/cache/OrderVolumeCache.java
  src/main/java/com/r307/arbitrader/service/event/TickerEventListener.java
  src/main/java/com/r307/arbitrader/service/paper/PaperAccountService.java
  src/main/java/com/r307/arbitrader/service/paper/PaperExchange.java
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
  src/test/java/com/r307/arbitrader/BaseTestCase.java
  src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
  src/test/java/com/r307/arbitrader/service/ExchangeServiceTest.java
  src/test/java/com/r307/arbitrader/service/TickerServiceTest.java
  src/test/java/com/r307/arbitrader/service/cache/ExchangeBalanceCacheTest.java
  src/test/java/com/r307/arbitrader/service/cache/ExchangeFeeCacheTest.java
  src/test/java/com/r307/arbitrader/service/cache/OrderVolumeCacheTest.java
  src/test/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategyTest.java
Labels: tech debt

#310 new banner suggested by @froque on Discord
  build.gradle
  src/main/resources/banner.txt
Labels: enhancement

#311 Correct fee calculation
  src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
Labels: bug

#309 When step size is available then adjust total amount (with fee included) by the step size using TradingService#roundByStep
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug

#314 Fix trade log inconsistency when slip occurs
  src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
  src/main/java/com/r307/arbitrader/service/TradingService.java
Labels: bug

#317 Cache Exchange's fee on the last fall back return - when calling ExchangeService#getExchangeFee
  src/main/java/com/r307/arbitrader/service/ExchangeService.java
Labels: bug

#319 some new configuration options
  application.example.yaml
  src/main/java/com/r307/arbitrader/config/PaperConfiguration.java
  src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
  src/main/java/com/r307/arbitrader/service/SpreadService.java
  src/main/java/com/r307/arbitrader/service/TradingScheduler.java
  src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
  src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Labels: enhancement
